import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/layout/Header";
import Footer from "@/layout/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Macular Industries Private Limited",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header/>
      <body
        
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        {children}
        <Footer/>
      </body>
    </html>
  );
}
