import Header from "@/layout/Header";
import Footer from "@/layout/Footer";
import "./globals.css";

export const metadata = {
  title: "Macular Industries Private Limited",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
